// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://koygfeonfswgqhoqqbnm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtveWdmZW9uZnN3Z3Fob3FxYm5tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3Nzk1MTgsImV4cCI6MjA2MDM1NTUxOH0.0ZcGjQKR625ARlyqVcqd_4Fmy43onIjLQdnWhfRNs1k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);